import { formTypes, currencyPlaceholder, percentSign } from '../common/appConstants';

const fields = [
  {
    label: 'Project name',
    name: 'projectName',
    type: formTypes.TEXT,
    defVal: '',
    required: true,
  },
  {
    label: 'Post code',
    name: 'postCode',
    type: formTypes.TEXT,
    defVal: '',
    required: true,
  },
  {
    label: `Asking price(${currencyPlaceholder})`,
    name: 'askingPrice',
    type: formTypes.NUMBER,
    defVal: 0,
  },
  {
    label: `Purchase price(${currencyPlaceholder})`,
    name: 'propertyValue',
    type: formTypes.NUMBER,
    defVal: 0,
  },
  {
    label: `Done up value(${currencyPlaceholder})`,
    name: 'doneUpValue',
    type: formTypes.NUMBER,
    defVal: 0,
  },
  {
    label: 'Cash purchase',
    name: 'buyingCash',
    type: formTypes.CHECKBOX,
    defVal: 'no',
  },
  {
    label: `Initial LTV(${percentSign})`,
    name: 'initialLoanToValue',
    type: formTypes.NUMBER,
    defVal: 75,
    disabled: [{ whenField: 'buyingCash', regex: /yes/ }],
  },
  {
    label: `Mortgage fee(${currencyPlaceholder})`,
    name: 'initMortgageFee',
    type: formTypes.NUMBER,
    defVal: 0,
    disabled: [{ whenField: 'buyingCash', regex: /yes/ }],
  },
  {
    label: `Surveyors fee(${currencyPlaceholder})`,
    name: 'initSurveyorsFee',
    type: formTypes.NUMBER,
    defVal: 600,
  },
  {
    label: `Legal fees(${currencyPlaceholder})`,
    name: 'initLegalFee',
    type: formTypes.NUMBER,
    defVal: 1500,
  },
  {
    label: 'Stamp duty type',
    name: 'stampDutyType',
    type: formTypes.SELECT,
    options: [
      { value: 'residential', name: 'Residential' },
      { value: 'commercial', name: 'Commercial' },
    ],
    defVal: 'residential',
  },
  {
    label: 'Stamp duty region',
    name: 'stampDutyRegion',
    type: formTypes.SELECT,
    options: [
      { value: 'england', name: 'England/NI' },
      { value: 'scotland', name: 'Scotland' },
      { value: 'wales', name: 'Wales' },
      { value: 'ireland', name: 'Ireland' },
    ],
    defVal: 'england',
  },
  {
    label: 'Stamp duty buyer',
    name: 'stampDutyBuyer',
    type: formTypes.SELECT,
    options: [
      { value: 'investor', name: 'Investor' },
      { value: 'first', name: 'First time buyer' },
      { value: 'home', name: 'Moving house' },
    ],
    defVal: 'investor',
    disabled: [{ whenField: 'stampDutyType', regex: /commercial/ }],
  },
  {
    label: `Monthly rent(${currencyPlaceholder})`,
    name: 'monthlyRent',
    type: formTypes.NUMBER,
    defVal: 0,
    disabled: [{ whenField: 'dealType', regex: /^((?!btl).)*$/ }],
  },
  {
    label: 'Deal type',
    name: 'dealType',
    type: formTypes.SELECT,
    options: [
      { value: 'btl&flip', name: 'Buy to let and flip' },
      { value: 'btl', name: 'Buy to let' },
      { value: 'flip', name: 'Flip' },
      { value: 'home', name: 'Home only' },
    ],
    defVal: 'btl&flip',
  },
  {
    label: `Refurbishment cost(${currencyPlaceholder})`,
    name: 'refurbCost',
    type: formTypes.NUMBER,
    defVal: 0,
  },
  {
    label: `Other cost(${currencyPlaceholder})`,
    name: 'otherCost',
    type: formTypes.NUMBER,
    defVal: 0,
  },
  {
    label: `Remortgage fee(${currencyPlaceholder})`,
    name: 'remortgageFee',
    type: formTypes.NUMBER,
    defVal: 0,
    disabled: [{ whenField: 'dealType', regex: /^((?!btl).)*$/ }],
  },
  {
    label: `Remortgage valuation fee(${currencyPlaceholder})`,
    name: 'remortgageValuationFee',
    type: formTypes.NUMBER,
    defVal: 0,
    disabled: [{ whenField: 'dealType', regex: /^((?!btl).)*$/ }],
  },
  {
    label: `Remortgage legal fees(${currencyPlaceholder})`,
    name: 'remortgageLegalFee',
    type: formTypes.NUMBER,
    defVal: 0,
    disabled: [{ whenField: 'dealType', regex: /^((?!btl).)*$/ }],
  },
  {
    label: 'Repairing lease',
    name: 'repairingLease',
    type: formTypes.CHECKBOX,
    defVal: 'no',
    disabled: [{ whenField: 'dealType', regex: /^((?!btl).)*$/ }],
  },
  {
    label: `Letting agents rate(${percentSign})`,
    name: 'agentsPercent',
    type: formTypes.NUMBER,
    defVal: 10,
    disabled: [
      { whenField: 'dealType', regex: /^((?!btl).)*$/ },
      { whenField: 'repairingLease', regex: /yes/ },
    ],
  },
  {
    label: `
    MOE rate(${percentSign})`,
    name: 'moePercent',
    type: formTypes.NUMBER,
    defVal: 15,
    disabled: [
      { whenField: 'dealType', regex: /^((?!btl).)*$/ },
      { whenField: 'repairingLease', regex: /yes/ },
    ],
  },
  {
    label: 'Mortgage term',
    name: 'mortgageTerm',
    type: formTypes.NUMBER,
    defVal: 25,
  },
  {
    label: `Interest rate(${percentSign})`,
    name: 'mortgageInterestRatePercent',
    type: formTypes.NUMBER,
    defVal: 6.0,
  },
  {
    label: `Remortgage LTV(${percentSign})`,
    name: 'loanToValue',
    type: formTypes.NUMBER,
    defVal: 75,
    disabled: [{ whenField: 'dealType', regex: /^((?!btl).)*$/ }],
  },
  {
    label: `Solicitors selling fee(${currencyPlaceholder})`,
    name: 'sellingLegalFee',
    type: formTypes.NUMBER,
    defVal: 0,
    disabled: [{ whenField: 'dealType', regex: /^((?!flip).)*$/ }],
  },
  {
    label: `Agent/selling fee(${currencyPlaceholder})`,
    name: 'agentSellingFee',
    type: formTypes.NUMBER,
    defVal: 0,
    disabled: [{ whenField: 'dealType', regex: /^((?!flip).)*$/ }],
  },
  {
    label: `Mortgage stress test(${percentSign})`,
    name: 'mortgageStressMultipePercent',
    type: formTypes.NUMBER,
    defVal: 125,
    disabled: [{ whenField: 'dealType', regex: /^((?!btl).)*$/ }],
  },
  {
    label: `Stress interest rate(${percentSign})`,
    name: 'mortgageStressInterestRatePercent',
    type: formTypes.NUMBER,
    defVal: 5.0,
    disabled: [{ whenField: 'dealType', regex: /^((?!btl).)*$/ }],
  },
];

export default fields;
